### ISSUE TITLE
I met a "index out of range"

### ISSUE THREAD

**Issue by 3xxx** [tealeg/xlsx#200]
They like the same excel,but the different results.
my code:
```
package main

import (
    "fmt"
    "strconv"
    "github.com/tealeg/xlsx"
)
package main

import (
    "fmt"
    "strconv"
    "github.com/tealeg/xlsx"
)

type Catalog struct {
    Id          int64
    Name        string
    ParentId    int64
    Tnumber     string
    Drawn       string
    Designd     string
    Checked     string
    Emamined    string
    Verified    string
    Approved    string
    Data        string
    DesignStage string
    Section     string
    Projec      string
    Author      string
    Exist       bool
    TopicId     int64
}

func main() {
    test5()
}
func test5() {
    //  path := "D:/panic.xlsx"
    path := "D:/ok.xlsx"
    xlFile, _ := xlsx.OpenFile(path) //excelFileName

    var catalog Catalog
    for _, sheet := range xlFile.Sheets {
        for _, row := range sheet.Rows {
            j := 1
            catalog.Tnumber = row.Cells[j].String()
            catalog.Name = row.Cells[j+1].String()
            catalog.Drawn = row.Cells[j+2].String()
            catalog.Designd = row.Cells[j+3].String()
            catalog.Checked = row.Cells[j+4].String()
            catalog.Emamined = row.Cells[j+5].String()
            catalog.Verified = row.Cells[j+6].String()
            catalog.Approved = row.Cells[j+7].String()
            catalog.Data = row.Cells[j+8].String()
            catalog.DesignStage = row.Cells[j+9].String()
            catalog.Section = row.Cells[j+10].String()
            catalog.Projec = row.Cells[j+11].String()
            fmt.Printf("%s\n", catalog)
        }
    }
}
```
```
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x849fe0, 0xc082008060)
	D:/Go/src/runtime/panic.go:464 +0x3f4
main.test5()
	D:/gowork/src/test_go/excel.go:146 +0x83e
main.main()
	D:/gowork/src/test_go/excel.go:35 +0x1b
```
the panic file:[panic.xlsx](https://github.com/3xxx/HydroCMS/files/163018/panic.xlsx)
the ok file:[ok.xlsx](https://github.com/tealeg/xlsx/files/163053/ok.xlsx)

**Comment by tealeg** [comment]
@3xxx your panic.xlsx file doesn't have any cells in it's first row (sheet.Rows[0]) which means your attempt to access "row.Cells[j].String()" (where j=1) is trying to index a cell that doesn't exist on the very first time your program loops.

*Always* check the bounds of arrays before indexing them.
