### ISSUE TITLE
Panic on xlsx.Save

### ISSUE THREAD

**Issue by Dexus** [tealeg/xlsx#644]
@tealeg linke in #638 we have still a problem

PANIC File Storage

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6cc17f]

goroutine 1 [running]:
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1.1(0xc000c2f200, 0x1, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:610 +0x1df
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell.func1(0x9, 0xc000c2f200, 0x0, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/memory.go:94 +0x84
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell(0xc00095cff0, 0xc00050fe90, 0xc00000e6d0, 0x1, 0x1, 0xc000045400, 0x6b8854)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/memory.go:98 +0x10a
github.com/tealeg/xlsx/v3.(*Row).ForEachCell(...)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/row.go:116
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1(0xc000b16540, 0xc000b16540, 0x17)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:643 +0x102
github.com/tealeg/xlsx/v3.(*Sheet).ForEachRow(0xc00067ea80, 0xc000045518, 0xc0000454e8, 0x1, 0x1, 0xc0003bdc20, 0x796ee8)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:187 +0x283
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows(0xc00067ea80, 0xc0036d19e0, 0x0, 0xc000268600, 0xc000226080)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:646 +0x11b
github.com/tealeg/xlsx/v3.(*Sheet).MarshalSheet(0xc00067ea80, 0x7db7a0, 0xc000268640, 0xc00050f800, 0xc00017cc60, 0x0, 0x0, 0x10)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:861 +0x1e9
github.com/tealeg/xlsx/v3.(*File).MarshallParts(0xc000182180, 0xc000045d40, 0x1000, 0xc00022d000)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:472 +0x84f
github.com/tealeg/xlsx/v3.(*File).Write(0xc000182180, 0x7dc3a0, 0xc00000e0c8, 0xc0000001b6, 0xc00000e0c8)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:158 +0xef
github.com/tealeg/xlsx/v3.(*File).Save(0xc000182180, 0x790555, 0x65, 0xc0036d18c0, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:141 +0x16d
main.main()
        /home/josef/Dokumente/git/rentonion/main.go:94 +0x558
exit status 2
```

PANIC Memory Storage
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x6cc1df]

goroutine 1 [running]:
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1.1(0xc000a870e0, 0x1, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:610 +0x1df
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell.func1(0x9, 0xc000a870e0, 0x0, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/memory.go:94 +0x84
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell(0xc0006d4ae0, 0xc001b407b0, 0xc0000a6ac0, 0x1, 0x1, 0xc00007d3f8, 0x6b88b4)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/memory.go:98 +0x10a
github.com/tealeg/xlsx/v3.(*Row).ForEachCell(...)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/row.go:116
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1(0xc0004b3500, 0xc0004b3500, 0x17)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:643 +0x102
github.com/tealeg/xlsx/v3.(*Sheet).ForEachRow(0xc0004c8480, 0xc00007d510, 0xc00007d4e0, 0x1, 0x1, 0xc000e7b8c0, 0x797068)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:187 +0x283
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows(0xc0004c8480, 0xc004265320, 0x0, 0xc00005c000, 0xc002864080)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:646 +0x11b
github.com/tealeg/xlsx/v3.(*Sheet).MarshalSheet(0xc0004c8480, 0x7db920, 0xc00005c0f0, 0xc001b40330, 0xc000108b00, 0x0, 0x0, 0x10)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/sheet.go:861 +0x1e9
github.com/tealeg/xlsx/v3.(*File).MarshallParts(0xc00010e180, 0xc00007dd38, 0x1000, 0xc000185000)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:472 +0x84f
github.com/tealeg/xlsx/v3.(*File).Write(0xc00010e180, 0x7dc520, 0xc0000a6208, 0xc0000001b6, 0xc0000a6208)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:158 +0xef
github.com/tealeg/xlsx/v3.(*File).Save(0xc00010e180, 0x7906d5, 0x65, 0xc004265200, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.2/file.go:141 +0x16d
main.main()
        /home/josef/Dokumente/git/rentonion/main.go:94 +0x579
```

CODE:

```go
// open an existing file
	wbFile, err := xlsx.OpenFile(fileToOpen, xlsx.UseMemoryCellStore) // which Store we use make no difference...
	if err != nil {
		panic(err)
	}

	// wbFile now contains a reference to the workbook
	// show all the sheets in the workbook
	fmt.Println("Sheets in this file:")
	for i, sh := range wbFile.Sheets {
		fmt.Println(i, sh.Name)
	}
	fmt.Println("----")

	sheetName := "Geräte"
	sh, ok := wbFile.Sheet[sheetName]
	if !ok {
		fmt.Println("Sheet does not exist")
		return
	}
	fmt.Println("Max row in sheet:", sh.MaxRow)
	//err = sh.ForEachRow(rowVisitor)
	//fmt.Println("Err=", err)

	time.Sleep(1 * time.Second)

	cell, err := sh.Cell(2, 107)
	if err != nil {
		panic(err)
	}
	colNum, rowNum, _ := xlsx.GetCoordsFromCellIDString("DD3000")
	fmt.Println("DD3:", cell.Formula())
	cell, err = sh.Cell(rowNum, colNum)
	if err != nil {
		panic(err)
	}
	cell.SetInt64(39491)

	err = wbFile.Save(fileToOpen + "_demo.xlsx") // line 94
	if err != nil {
		panic(err)
	}
```

**Comment by tealeg** [comment]
Thanks, I'll take a look.

**Comment by tealeg** [comment]
OK, I am able to reproduce it using the code above, so I should be able to resolve it.

**Comment by tealeg** [comment]
@Dexus I've cut a 3.2.3 release with this fix in it.

oh ... und grüße aus Hannover ;-)

**Comment by Dexus** [comment]
@tealeg Thank you!

Grüße aus Osnabrück 😉

**Comment by Dexus** [comment]
@tealeg 
I still have the same issue.

```
go run  .
Sheets in this file:
0 1. Investitionen
1 2. GuV
2 3. Liquidität
3 4. Kapitalbedarf
4 5. Rentabilität
5 Personalkosten
6 Geräte
7 AllgemeineKosten
8 Variablen
9 Feiertage
10 Grafiken & Tabellen
----
Max row in sheet: 188
DD3: NETWORKDAYS.INTL(DD13,EOMONTH(DD13,0),1,Feiertage!$C:$C)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x63083f]

goroutine 1 [running]:
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1.1(0xc0004fb440, 0x1, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/sheet.go:610 +0x1df
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell.func1(0x9, 0xc0004fb440, 0x0, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/memory.go:94 +0x84
github.com/tealeg/xlsx/v3.(*MemoryRow).ForEachCell(0xc000919260, 0xc000db9770, 0xc00000eb58, 0x1, 0x1, 0xc00008d410, 0x61cf14)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/memory.go:98 +0x10a
github.com/tealeg/xlsx/v3.(*Row).ForEachCell(...)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/row.go:116
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows.func1(0xc000534100, 0xc000534100, 0x17)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/sheet.go:643 +0x102
github.com/tealeg/xlsx/v3.(*Sheet).ForEachRow(0xc0007c03c0, 0xc00008d528, 0xc00008d4f8, 0x1, 0x1, 0xc0008b1d40, 0x7a5448)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/sheet.go:187 +0x283
github.com/tealeg/xlsx/v3.(*Sheet).prepWorksheetFromRows(0xc0007c03c0, 0xc0025c6c60, 0x0, 0xc0000d0100, 0xc001dac9e0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/sheet.go:646 +0x11b
github.com/tealeg/xlsx/v3.(*Sheet).MarshalSheet(0xc0007c03c0, 0x7eb1e0, 0xc0000d01e0, 0xc000db92f0, 0xc000146c60, 0x0, 0x0, 0x10)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/sheet.go:861 +0x1e9
github.com/tealeg/xlsx/v3.(*File).MarshallParts(0xc000106180, 0xc00008dd50, 0x1000, 0xc0001f9000)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/file.go:474 +0x80f
github.com/tealeg/xlsx/v3.(*File).Write(0xc000106180, 0x7ebde0, 0xc00000e500, 0x1b6, 0xc00000e500)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/file.go:158 +0xef
github.com/tealeg/xlsx/v3.(*File).Save(0xc000106180, 0x79ea50, 0x65, 0xc0025c6b40, 0x0)
        /home/josef/go/pkg/mod/github.com/tealeg/xlsx/v3@v3.2.3/file.go:141 +0x16d
main.main()
        /home/josef/Dokumente/git/rentonion/main.go:58 +0x4fb
```

sheets.go:610
```
for _, rel := range relations.Relationships {
```

relations is nil


here a test xlsx that i use:
[finanzplan_test.xlsx](https://github.com/tealeg/xlsx/files/5544870/finanzplan_test.xlsx)


gocode:
```

func main() {
	// open an existing file
	wbFile, err := xlsx.OpenFile(fileToOpen)
	if err != nil {
		panic(err)
	}

	// wbFile now contains a reference to the workbook
	// show all the sheets in the workbook
	fmt.Println("Sheets in this file:")
	for i, sh := range wbFile.Sheets {
		fmt.Println(i, sh.Name)
	}
	fmt.Println("----")

	sheetName := "2.2. Maschinen"
	sh, ok := wbFile.Sheet[sheetName]
	if !ok {
		fmt.Println("Sheet does not exist")
		return
	}
	fmt.Println("Max row in sheet:", sh.MaxRow)
	//err = sh.ForEachRow(rowVisitor)
	//fmt.Println("Err=", err)

	time.Sleep(1 * time.Second)

	cell, err := sh.Cell(2, 107)
	if err != nil {
		panic(err)
	}
	fmt.Println("DD3:", cell.Formula())

	//colNum, rowNum, _ := excelize.CellNameToCoordinates("DD3")
	colNum, rowNum, _ := xlsx.GetCoordsFromCellIDString("DD3000")

	cell, err = sh.Cell(rowNum, colNum)
	if err != nil {
		panic(err)
	}
	if cell != nil {
		cell.SetInt64(39491)
	}

	err = wbFile.Save(fileToOpen + "_demo.xlsx")
	if err != nil {
		panic(err)
	}
	fmt.Println("Max row in sheet:", sh.MaxRow)

	time.Sleep(1 * time.Second)

}
```

~~~~
Es scheint mir als wenn https://github.com/tealeg/xlsx/blob/master/sheet.go#L610-L614 in ein `if relations != nil` gepackt werden sollte. Aber danach wird die XLSX (Excel 2019) zerstört mit der Excel Reparatur beim öffnen.

Vielleicht hilft das noch etwas.

**Comment by tealeg** [comment]
Though it looks the same, it's actually a different bug (with the same ultimate result).  I'll transfer this to a knew bug number.
